### ISSUE TITLE
Colon missing

### ISSUE THREAD

**Issue by gargi** [SoftwareEngineeringToolDemos/ICSE-2014-ImpactMiner#4]
Here is the link to the Original Project Page Here is the link to the Video showing the demonstration of the tool.
Instead of embedding the links in the sentence itself. There should be a colon followed by the embedded links.

**Comment by smalleni** [comment]
Looks like I'm missing something. But how is this a problem? Where does it explicityly say I have to use a colon?  This is what I found i nthe grading rubric 
Does the readme use embedded links (e.g. "[The Official Project Page](http://tools.hats-project.eu)" rather than "The Official Project Page: http://tools.hats-project.eu") properly? [link-mechanics]
Correct me if I'm wrong.

**Comment by gargi** [comment]
Hi,
It does not have to be in that colon format as such. I created this issue under the following grading rubric:
Is the readme grammatically correct and use correct spacing and punctuation? [writing-mechanics]
As it did not seem grammatically correct nor did it have proper punctuation, I resolved it by changing it to the convention presented in the sample repository.
